### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by ndekross** [ryuran/stylus-svg#14]
Hi, 

Thanks for the plugin — this is exactly what I need. I cannot figure out how to use it though. 

```stylus
use('/node_modules/svg-stylus/index.js')

.foo
  background-image: svgImport('test.svg') 
```

compiles to

```css
.foo {
  background-image: svgImport('test.svg');
}
```

WAIDW?

Thanks.
